:figure-caption: Рисунок
:table-caption: Таблица
== 2 Функциональное назначение == 

=== 2.1 Назначение программы
Комплект СПО ОКН-М предназначен для получения, хранения и доведение до потребителей информации об объектах наблюдения (ОН) в околоземном пространстве (ОКП) с использованием управляемых из единого центра оптико-электронных, радиотехнических и радиолокационных средств мониторинга ОКП, географически распределённых и размещённых в т.ч. вне территории Российской Федерации. 

=== 2.2 Решаемые задачи
Комплект CПО ОКН-М предназначен для решения следующих основных задач:

. Работа по запускам КА. 
. Приоритетные работы по вновь запущенным КА или ОН, образовавшимся в ОКП по иным причинам. 
. Выполнение заявок АЦУК-М, данные АСПОС (сближение, разрушение, увод на захоронение). 
. Сбор статистики. Первоначальное накопление информации по ОН в объёме, требуемом для классификации ОН. 
. Получение траекторной информации для самоюстировки и уточнения характеристик погрешностей координатной измерительной информации средств мониторинга из состава ОКН-М. 
. Обработка зарегистрированной информации на соответствие МСРЧ (соответствие или не соответствие заявке). Получение информации по ОН в режиме мониторинга ИРИ в рабочем диапазоне частот радиотехнических средств. Анализ информации, доступной в МСРЧ, и сопоставление данных объективного мониторинга ОКП с этой информацией. 
. Получение информации по ОН в режиме мониторинга в ИК-диапазоне. 
. Исследование характера изменения блеска малозаметных объектов. Накопление информации по малозаметным КО (МЗКО).
. Выполнение заявок организации уполномоченной Минцифры.

=== 2.3 Сведения о функциональных органичениях на применение

Комплект CПО ОКН-М применяется только в составе аппартно-программного комплекса ОКН-М.
