:figure-caption: Рисунок
:table-caption: Таблица

== 7 Выходные данные ==

//Характер и организация выходных данных +
//Формат, описание и способ кодирования выходных данных +
//Описание структуры выходных данных включает указание типов данных, диапазонов их значений, форматов представления и т.д.
//Пример:
//Выходными данными являются:
//– выводимая на экран графическая и текстовая информация (результаты анализа системы);
//– файлы в одном из графических форматов – копии изображения построенных характеристик (АЧХ, ФЧХ и т.д.);
//– текстовые файлы – отчеты о проведенных исследованиях в формате… ;
//– диагностика состояния системы и сообщения обо всех возникших ошибках.
//В зависимости от особенностей программы допускается введение дополнительных разделов.
//Содержание разделов допускается иллюстрировать пояснительными примерами, таблицами, схемами, графиками, примерами и т.п.

Состав выходной информации СПО ОКН-М:

. Информация об ОН:
.. Координатная:
* орбитальные параметры ОН;
* угловое положение ОН или источника радиоизлучения в топоцентрической горизонтальной системе координат, связанной с измерительным средством;
.. Некоординатная:
* информация о характеристиках радиоизлучений;
* значения яркости ОН и характеристик её изменения;
. Отчёты об электромагнитной обстановке, формируемой радиоизлучениями ОН в районах размещения ОКН и ОКН-РД;
. Результаты контроля применения по назначению разнородных;(оптикоэлектронных, радиотехнических и радиолокационных) специализированных и привлекаемых средств мониторинга;
. Результаты анализа характеристик зарегистрированных радиоизлучений ОН и рассчитанных в АПУ орбитальных параметров ОН;
. Результаты анализа информации, доступной в МСРЧ (*для сопоставления с п.4);
. Результаты оценки текущей и ожидаемой на интервале до одного года; электромагнитной обстановки, формируемой радиоизлучениями (радиосигналами) ОН в различных диапазонах частот;
. Результаты оценки максимально возможного количества радиоизлучающих ОН, находящихся в зоне радиовидимости, максимально возможного количества радиосигналов, источниками которых являются эти ОН, и ожидаемого уровня радиосигналов на входе приёмника;
. Текущие показатели функционирования ОКН-М;
.. количество функционирующих специализированных и привлекаемых средств с разбивкой по категориям (специализированные и привлекаемые оптико-электронные, радиотехнические, радиолокационные);
.. количество не функционирующих специализированных и привлекаемых средств с разбивкой по категориям (временно не работоспособно - на техническом обслуживании, временно не работоспособно - отказ оборудования, отсутствие метеоусловий для проведения наблюдений, отсутствие условий по освещённости);
.. параметры охвата ОКП (по высотам полёта ОН на участках мониторинга, по наклонениям орбит, по долготам подспутниковых точек ОН в области геостационарной орбиты) и динамика их изменения;
.. количество ОН, по которым имеется информация мониторинга, и объём накопленной информации с разбивкой по различным группам: по типу ОН - ракеты-носители (ступени ракет-носителей), разгонные блоки (ступени разгонных блоков), функционирующие и не функционирующие КА, прочие техногенные КО; по категориям заметности раздельно для оптических, радиолокационных и радиотехнических средств; по размещению в различных областях ОКП;
.. распределение количества ОН по значению максимального перерыва по времени в получении информации мониторинга (раздельно и совместно для оптико-электронных, радиотехнических и радиолокационных средств) на интервале анализа 7 сут, 30 сут, 180 сут, 1 год;
.. количество ОН, по которым получена информация в предшествующие 24 ч.
.. количество ОН, по которым ожидается получение информации в следующие 24 ч.;
.. области ОКП, просмотренные оптико-электронными, радиотехническими и радиолокационными средствами в предыдущие 24 ч.;
.. области ОКП, которые планируется просмотреть оптикоэлектронными, радиотехническими и радиолокационными средствами в следующие 24 ч.;
. Документ с полным перечнем ОН;
. Отчёты об изменении текущих показателей функционирования ОКН-М;
. Графические формы, иллюстрирующие текущие показатели функционирования ОКН-М и их изменение с течением времени;
. Перечень направлений информационного взаимодействия ОКН-М с внешними абонентами и составных частей ОКН-М между собой. Номенклатура сообщений, циркулирующих при осуществлении информационного взаимодействия;
. Результаты анализа информации функционального контроля составных частей ОКН-М;
. Перечень плановых и внеочередных работ по техническому обслуживанию и ремонту составных частей ОКН-М и привлекаемых средств;
. Результаты контроля расходования ресурса составных частей ОКН-М;
. Результаты контроля информационного взаимодействия ОКН-М с внешними абонентами и составных частей ОКН-М между собой;
. Отчёты по результатам обработки и анализа разнородной измерительной координатной, некоординатной и прочей информации, получаемой от специализированных и привлекаемых средств;
. Отчёты по результатам обработки и анализа об орбитальном движении ОН, физических характеристиках и характеристиках радиоизлучений ОН;
. Отчёты по результатам обработки и анализа информации о характеристиках погрешностей измерительной координатной и некоординатной информации, получаемой специализированными и привлекаемыми средств мониторинга;
. Информация о новых обнаруженных ОН;
. Результаты оценки параметров орбитального движения ОН по результатам совместной обработки оптической, радиотехнической и радиолокационной координатной информации;
. Информация об астроклиматических и метеорологических условиях в районах размещения специализированных средств;
. Информация о результатах планирования применения специализированных и привлекаемых средств;
. Информация выполнении заявок, полученных от АЦУК-М;
. Информация о результатах отождествления источников обнаруженных радиоизлучений с ОН в ЦБД;
. Информация о результатах выполнения заявок, полученных от уполномоченной Минцифры России организации;
. Информация в СКШ1АД-У и АПК ОДМ-У;
. Результаты анализа и информация о техническом состоянии и надёжности ОКН-М на всех этапах его создания, испытаний и эксплуатации в соответствии с требованиями Положения РК-11-КТ, ГОСТ РО 1410-002-2010, ГОСТ РВ 51030-97.
